[Writable]
LogLevel = 'DEBUG'

[Service]
Host = "10.109.24.136"
Port = 49990
ConnectRetries = 20
Labels = []
OpenMsg = "device simple started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "10.109.24.88"
Port = 8500
Type = "consul"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "10.109.24.88"
  Port = 48080
  Timeout = 5000
  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "10.109.24.88"
  Port = 48081
  Timeout = 5000
  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "10.109.24.88"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "E:\\workspace-edgex\\src\\github.com\\edgexfoundry\\edgex-ui-go\\vds\\simpledevice\\res"

[Logging]
EnableRemote = false
File = "./device-simple.log"

# Pre-define Devices
[[DeviceList]]
  Name = "Simple-Device-02"
  Profile = "Simple-Device"
  Description = "Example of Simple Device"
  Labels = [ "industrial" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "simple01"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "1000s"
    OnChange = false
    Resource = "Switch"
  [[DeviceList.AutoEvents]]
    Frequency = "3000s"
    OnChange = false
    Resource = "Image"
